# Generated by Django 2.1.4 on 2019-02-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='index.Author'),
        ),
    ]
